//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KROsipovaItog1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч акта приемки.
    /// </summary>
    // *** Start programmer edit section *** (ТЧАктаПриемки CustomAttributes)

    // *** End programmer edit section *** (ТЧАктаПриемки CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч акта приемки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧАктаПриемкиE", new string[] {
            "НомерПозиции as \'Номер позиции\'",
            "Склад as \'Склад\'",
            "Склад.ИмяСклада as \'Имя склада\'",
            "ТН as \'ТН\'",
            "ТН.Колво as \'Колво\'"}, Hidden=new string[] {
            "Склад.ИмяСклада",
            "ТН.Колво"})]
    [MasterViewDefineAttribute("ТЧАктаПриемкиE", "Склад", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ИмяСклада")]
    [MasterViewDefineAttribute("ТЧАктаПриемкиE", "ТН", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Колво")]
    [View("ТЧАктаПриемкиL", new string[] {
            "НомерПозиции as \'Номер позиции\'",
            "Склад.ИмяСклада as \'Имя склада\'",
            "ТН.Колво as \'Колво\'"})]
    public class ТЧАктаПриемки : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПозиции;
        
        private IIS.KROsipovaItog1.Склад fСклад;
        
        private IIS.KROsipovaItog1.ТН fТН;
        
        // *** Start programmer edit section *** (ТЧАктаПриемки CustomMembers)

        // *** End programmer edit section *** (ТЧАктаПриемки CustomMembers)

        
        /// <summary>
        /// НомерПозиции.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции CustomAttributes)
        public virtual int НомерПозиции
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get start)
                int result = this.fНомерПозиции;
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set start)
                this.fНомерПозиции = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.НомерПозиции Set end)
            }
        }
        
        /// <summary>
        /// Т ч акта приемки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.Склад CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual IIS.KROsipovaItog1.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Склад Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Склад Get start)
                IIS.KROsipovaItog1.Склад result = this.fСклад;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Склад Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.Склад Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.Склад Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.Склад Set end)
            }
        }
        
        /// <summary>
        /// Т ч акта приемки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктаПриемки.ТН CustomAttributes)

        // *** End programmer edit section *** (ТЧАктаПриемки.ТН CustomAttributes)
        [PropertyStorage(new string[] {
                "ТН"})]
        [NotNull()]
        public virtual IIS.KROsipovaItog1.ТН ТН
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.ТН Get start)

                // *** End programmer edit section *** (ТЧАктаПриемки.ТН Get start)
                IIS.KROsipovaItog1.ТН result = this.fТН;
                // *** Start programmer edit section *** (ТЧАктаПриемки.ТН Get end)

                // *** End programmer edit section *** (ТЧАктаПриемки.ТН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктаПриемки.ТН Set start)

                // *** End programmer edit section *** (ТЧАктаПриемки.ТН Set start)
                this.fТН = value;
                // *** Start programmer edit section *** (ТЧАктаПриемки.ТН Set end)

                // *** End programmer edit section *** (ТЧАктаПриемки.ТН Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧАктаПриемкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧАктаПриемкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧАктаПриемкиE", typeof(IIS.KROsipovaItog1.ТЧАктаПриемки));
                }
            }
            
            /// <summary>
            /// "ТЧАктаПриемкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧАктаПриемкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧАктаПриемкиL", typeof(IIS.KROsipovaItog1.ТЧАктаПриемки));
                }
            }
        }
    }
}
