version: '3'

services:
  app:
    image: krosipovaitog1/app
    links:
      - app-postgres-db:app-postgres-db
    ports:
      - 80:80

  app-postgres-db:
    image: krosipovaitog1/postgre-sql
    volumes:
      - DB:/var/lib/pgsql/data/
volumes:
  DB:
